/*
 This software is the confidential information and copyrighted work of
 NetCracker Technology Corp. ("NetCracker") and/or its suppliers and
 is only distributed under the terms of a separate license agreement
 with NetCracker.
 Use of the software is governed by the terms of the license agreement.
 Any use of this software not in accordance with the license agreement
 is expressly prohibited by law, and may result in severe civil
 and criminal penalties. 
 
 Copyright (c) 1995-2016 NetCracker Technology Corp.
 
 All Rights Reserved.
 
*/
Rem
Rem    NAME
Rem      create_ncdba_user.sql
Rem
Rem    DESCRIPTION
Rem      This script creates NetCracker Database Administratirve account and grant all necessary permissions to it. 
Rem      This account is used for NetCracker product deployment, maintenance and troubleshooting.
Rem      Before runnig this script 
Rem      1. Change NCDBA user name if needed. The default one is NC_ADMIN.
Rem      2. Change NCDBA user password if needed. The default one is NC_ADMIN.
Rem
Rem    MODIFIED   (YY/MM/DD)- NOTES
Rem    anko0506    09/18/12 - initial version
Rem    debu        05/25/15 - default username/password corrected
Rem    debu        05/26/15 - privileges for PSE component added
Rem    debu        06/09/16 - privilege for select sys.v_$parameter added
Rem

SET DEFINE ON

DEFINE NCDBA_USER_NAME = 'NC_ADMIN'
DEFINE NCDBA_PASSWORD = 'NC_ADMIN'

CREATE USER &&NCDBA_USER_NAME
                IDENTIFIED BY &&NCDBA_PASSWORD
                DEFAULT TABLESPACE NC_DATA
                TEMPORARY TABLESPACE NC_TEMP
                ACCOUNT UNLOCK;

/* Administrative privileges */
GRANT CREATE USER TO &&NCDBA_USER_NAME;
GRANT DROP USER TO &&NCDBA_USER_NAME;
/* End */

/* Privileges requered for NetCracker Core Product and built-in modules */
GRANT CREATE JOB TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SESSION TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TABLE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TYPE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE VIEW TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ON sys.dbms_lock TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_scheduler  TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_crypto TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON xdb.dbms_xmldom TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON xdb.dbms_xmlparser TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT QUERY REWRITE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT SELECT_CATALOG_ROLE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
/* End */

/* Privileges requered for NetCracker RDB Lite Component */
GRANT CREATE EVALUATION CONTEXT TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE RULE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE RULE SET TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT SELECT ON DBA_EXTENTS TO &&NCDBA_USER_NAME WITH GRANT OPTION;
/* End */

/* Privileges requered for NetCracker RDB Component */
GRANT ALTER SESSION TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT ALTER USER to &&NCDBA_USER_NAME;
GRANT CREATE SESSION TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE JOB TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SNAPSHOT TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TABLE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TYPE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE VIEW TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ON sys.dbms_job TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_lob TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_lock TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_sql TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_utility TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON xdb.dbms_xmldom TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON xdb.dbms_xmlschema TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.dba_data_files TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.dba_free_space TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.dba_temp_files TO &&NCDBA_USER_NAME WITH GRANT OPTION;
/* End */

/* Privileges requered for NetCracker RDB Light Component */
GRANT CREATE EVALUATION CONTEXT TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE RULE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE RULE SET TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT SELECT ON sys.dba_extents TO &&NCDBA_USER_NAME WITH GRANT OPTION;
/* End */

/* Privileges requered for NetCracker BAM Component */
GRANT CREATE SESSION TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE JOB TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TABLE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE VIEW TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ON sys.dbms_scheduler TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT_CATALOG_ROLE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT SELECT ON sys.v_$parameter TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT UNLIMITED TABLESPACE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
/* End */

/* Privileges requered for NetCracker HDS Component */
GRANT CREATE DATABASE LINK TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE JOB TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE SESSION TO &&NCDBA_USER_NAME WITH ADMIN OPTION; 
GRANT CREATE SYNONYM TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TABLE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE TYPE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE VIEW TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ON sys.dbms_lock TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_scheduler TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON xdb.dbms_xmldom TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON xdb.dbms_xmlparser TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT QUERY REWRITE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT SELECT ON sys.dba_indexes TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.dba_segments TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT UNLIMITED TABLESPACE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ON sys.dbms_aq TO &&NCDBA_USER_NAME WITH GRANT OPTION;
/* End */

/* Privileges requered for upgrading NetCracker Search component from version X.Y.Z */
GRANT CREATE RULE SET TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT CREATE RULE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE SET TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE TO &&NCDBA_USER_NAME WITH ADMIN OPTION;
GRANT EXECUTE ON sys.dbms_apply_adm TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_aqadm TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_capture_adm TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_flashback TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_propagation_adm TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON sys.dbms_streams_adm TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.dba_apply TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.dba_apply_instantiated_objects TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.dba_capture TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON sys.v_$log_history TO &&NCDBA_USER_NAME WITH GRANT OPTION;
/* End */

/* Privileges requered for Address Management component*/
GRANT EXECUTE ON CTXSYS.CTX_CLS TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON CTXSYS.CTX_DDL TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON CTXSYS.CTX_DOC TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON CTXSYS.CTX_OUTPUT TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON CTXSYS.CTX_QUERY TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON CTXSYS.CTX_REPORT TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON CTXSYS.CTX_THES TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT EXECUTE ON CTXSYS.CTX_ULEXER TO &&NCDBA_USER_NAME WITH GRANT OPTION;
/* End */

/* Privileges requered for Parallel Script Executor component*/
GRANT SELECT ON SYS.V_$SESSION TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON SYS.V_$SQLAREA TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON SYS.V_$SQL_PLAN_STATISTICS_ALL TO &&NCDBA_USER_NAME WITH GRANT OPTION;
GRANT SELECT ON SYS.V_$TRANSACTION TO &&NCDBA_USER_NAME WITH GRANT OPTION;
/* End */
/*
 WITHOUT LIMITING THE FOREGOING, COPYING, REPRODUCTION, REDISTRIBUTION,
 REVERSE ENGINEERING, DISASSEMBLY, DECOMPILATION OR MODIFICATION
 OF THE SOFTWARE IS EXPRESSLY PROHIBITED, UNLESS SUCH COPYING,
 REPRODUCTION, REDISTRIBUTION, REVERSE ENGINEERING, DISASSEMBLY,
 DECOMPILATION OR MODIFICATION IS EXPRESSLY PERMITTED BY THE LICENSE
 AGREEMENT WITH NETCRACKER. 
 
 THIS SOFTWARE IS WARRANTED, IF AT ALL, ONLY AS EXPRESSLY PROVIDED IN
 THE TERMS OF THE LICENSE AGREEMENT, EXCEPT AS WARRANTED IN THE
 LICENSE AGREEMENT, NETCRACKER HEREBY DISCLAIMS ALL WARRANTIES AND
 CONDITIONS WITH REGARD TO THE SOFTWARE, WHETHER EXPRESS, IMPLIED
 OR STATUTORY, INCLUDING WITHOUT LIMITATION ALL WARRANTIES AND
 CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
 TITLE AND NON-INFRINGEMENT.
 
 Copyright (c) 1995-2016 NetCracker Technology Corp.
 
 All Rights Reserved.
*/